"""Initial schema with 14 agent tables

Revision ID: e2e3262da0a2
Revises: 
Create Date: 2026-02-13 16:19:17.453081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e3262da0a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('extraction_status', sa.String(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_date', 'documents', ['document_date'], unique=False)
    op.create_index('idx_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('idx_document_user_id', 'documents', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_document_id', 'audit_logs', ['document_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('clinical_allergies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('allergen', sa.String(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('allergy_type', sa.String(), nullable=True),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_allergy_deleted_at', 'clinical_allergies', ['deleted_at'], unique=False)
    op.create_index('idx_allergy_document_id', 'clinical_allergies', ['document_id'], unique=False)
    op.create_index('idx_allergy_is_active', 'clinical_allergies', ['is_active'], unique=False)
    op.create_index('idx_allergy_severity', 'clinical_allergies', ['severity'], unique=False)
    op.create_index('idx_allergy_user_id', 'clinical_allergies', ['user_id'], unique=False)
    op.create_table('clinical_conditions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('diagnosed_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('body_site', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('icd10_code', sa.String(), nullable=True),
    sa.Column('snomed_code', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_condition_deleted_at', 'clinical_conditions', ['deleted_at'], unique=False)
    op.create_index('idx_condition_document_id', 'clinical_conditions', ['document_id'], unique=False)
    op.create_index('idx_condition_icd10', 'clinical_conditions', ['icd10_code'], unique=False)
    op.create_index('idx_condition_status', 'clinical_conditions', ['status'], unique=False)
    op.create_index('idx_condition_user_id', 'clinical_conditions', ['user_id'], unique=False)
    op.create_table('clinical_immunizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vaccine_name', sa.String(), nullable=False),
    sa.Column('administration_date', sa.Date(), nullable=True),
    sa.Column('dose_number', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('administered_by', sa.String(), nullable=True),
    sa.Column('facility', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cvx_code', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_immunization_admin_date', 'clinical_immunizations', ['administration_date'], unique=False)
    op.create_index('idx_immunization_deleted_at', 'clinical_immunizations', ['deleted_at'], unique=False)
    op.create_index('idx_immunization_document_id', 'clinical_immunizations', ['document_id'], unique=False)
    op.create_index('idx_immunization_user_id', 'clinical_immunizations', ['user_id'], unique=False)
    op.create_index('idx_immunization_vaccine', 'clinical_immunizations', ['vaccine_name'], unique=False)
    op.create_table('clinical_lab_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('reference_range', sa.String(), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=True),
    sa.Column('abnormal_flag', sa.String(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('ordering_provider', sa.String(), nullable=True),
    sa.Column('lab_facility', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('loinc_code', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lab_deleted_at', 'clinical_lab_results', ['deleted_at'], unique=False)
    op.create_index('idx_lab_document_id', 'clinical_lab_results', ['document_id'], unique=False)
    op.create_index('idx_lab_is_abnormal', 'clinical_lab_results', ['is_abnormal'], unique=False)
    op.create_index('idx_lab_loinc', 'clinical_lab_results', ['loinc_code'], unique=False)
    op.create_index('idx_lab_test_date', 'clinical_lab_results', ['test_date'], unique=False)
    op.create_index('idx_lab_test_name', 'clinical_lab_results', ['test_name'], unique=False)
    op.create_index('idx_lab_user_id', 'clinical_lab_results', ['user_id'], unique=False)
    op.create_table('clinical_medications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescriber', sa.String(), nullable=True),
    sa.Column('indication', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rxnorm_code', sa.String(), nullable=True),
    sa.Column('ndc_code', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medication_deleted_at', 'clinical_medications', ['deleted_at'], unique=False)
    op.create_index('idx_medication_document_id', 'clinical_medications', ['document_id'], unique=False)
    op.create_index('idx_medication_is_active', 'clinical_medications', ['is_active'], unique=False)
    op.create_index('idx_medication_rxnorm', 'clinical_medications', ['rxnorm_code'], unique=False)
    op.create_index('idx_medication_user_id', 'clinical_medications', ['user_id'], unique=False)
    op.create_table('clinical_procedures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('procedure_name', sa.String(), nullable=False),
    sa.Column('performed_date', sa.Date(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('facility', sa.String(), nullable=True),
    sa.Column('body_site', sa.String(), nullable=True),
    sa.Column('indication', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cpt_code', sa.String(), nullable=True),
    sa.Column('icd10_pcs_code', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_procedure_cpt', 'clinical_procedures', ['cpt_code'], unique=False)
    op.create_index('idx_procedure_deleted_at', 'clinical_procedures', ['deleted_at'], unique=False)
    op.create_index('idx_procedure_document_id', 'clinical_procedures', ['document_id'], unique=False)
    op.create_index('idx_procedure_performed_date', 'clinical_procedures', ['performed_date'], unique=False)
    op.create_index('idx_procedure_user_id', 'clinical_procedures', ['user_id'], unique=False)
    op.create_table('clinical_vital_signs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('measurement_date', sa.DateTime(), nullable=True),
    sa.Column('systolic_bp', sa.Float(), nullable=True),
    sa.Column('diastolic_bp', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('temperature_unit', sa.String(), nullable=True),
    sa.Column('oxygen_saturation', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('height_unit', sa.String(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vital_deleted_at', 'clinical_vital_signs', ['deleted_at'], unique=False)
    op.create_index('idx_vital_document_id', 'clinical_vital_signs', ['document_id'], unique=False)
    op.create_index('idx_vital_measurement_date', 'clinical_vital_signs', ['measurement_date'], unique=False)
    op.create_index('idx_vital_user_id', 'clinical_vital_signs', ['user_id'], unique=False)
    op.create_table('document_processing_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=False),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('validation_issues', sa.JSON(), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('clinical_data', sa.JSON(), nullable=True),
    sa.Column('summaries', sa.JSON(), nullable=True),
    sa.Column('brief_summary', sa.Text(), nullable=True),
    sa.Column('urgency_level', sa.String(), nullable=True),
    sa.Column('agent_context', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_proc_document_id', 'document_processing_results', ['document_id'], unique=False)
    op.create_index('idx_proc_is_valid', 'document_processing_results', ['is_valid'], unique=False)
    op.create_index('idx_proc_quality', 'document_processing_results', ['quality_score'], unique=False)
    op.create_index('idx_proc_status', 'document_processing_results', ['processing_status'], unique=False)
    op.create_index('idx_proc_urgency', 'document_processing_results', ['urgency_level'], unique=False)
    op.create_table('document_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('brief_summary', sa.Text(), nullable=True),
    sa.Column('clinical_overview', sa.Text(), nullable=True),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('urgency_level', sa.String(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('treatment_plan', sa.JSON(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('semantic_keywords', sa.JSON(), nullable=True),
    sa.Column('clinical_relationships', sa.JSON(), nullable=True),
    sa.Column('temporal_events', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('missing_information', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_summary_document_id', 'document_summaries', ['document_id'], unique=False)
    op.create_index('idx_summary_urgency', 'document_summaries', ['urgency_level'], unique=False)
    op.create_table('search_terms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('term_type', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_document_id', 'search_terms', ['document_id'], unique=False)
    op.create_index('idx_search_term', 'search_terms', ['term'], unique=False)
    op.create_index('idx_search_term_type', 'search_terms', ['term_type'], unique=False)
    op.create_index(op.f('ix_search_terms_term'), 'search_terms', ['term'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_title', sa.String(), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('related_condition_id', sa.String(), nullable=True),
    sa.Column('related_medication_id', sa.String(), nullable=True),
    sa.Column('related_procedure_id', sa.String(), nullable=True),
    sa.Column('related_lab_result_id', sa.String(), nullable=True),
    sa.Column('importance', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('facility', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_timeline_deleted_at', 'timeline_events', ['deleted_at'], unique=False)
    op.create_index('idx_timeline_document_id', 'timeline_events', ['document_id'], unique=False)
    op.create_index('idx_timeline_event_date', 'timeline_events', ['event_date'], unique=False)
    op.create_index('idx_timeline_event_type', 'timeline_events', ['event_type'], unique=False)
    op.create_index('idx_timeline_importance', 'timeline_events', ['importance'], unique=False)
    op.create_index('idx_timeline_user_id', 'timeline_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timeline_user_id', table_name='timeline_events')
    op.drop_index('idx_timeline_importance', table_name='timeline_events')
    op.drop_index('idx_timeline_event_type', table_name='timeline_events')
    op.drop_index('idx_timeline_event_date', table_name='timeline_events')
    op.drop_index('idx_timeline_document_id', table_name='timeline_events')
    op.drop_index('idx_timeline_deleted_at', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_search_terms_term'), table_name='search_terms')
    op.drop_index('idx_search_term_type', table_name='search_terms')
    op.drop_index('idx_search_term', table_name='search_terms')
    op.drop_index('idx_search_document_id', table_name='search_terms')
    op.drop_table('search_terms')
    op.drop_index('idx_summary_urgency', table_name='document_summaries')
    op.drop_index('idx_summary_document_id', table_name='document_summaries')
    op.drop_table('document_summaries')
    op.drop_index('idx_proc_urgency', table_name='document_processing_results')
    op.drop_index('idx_proc_status', table_name='document_processing_results')
    op.drop_index('idx_proc_quality', table_name='document_processing_results')
    op.drop_index('idx_proc_is_valid', table_name='document_processing_results')
    op.drop_index('idx_proc_document_id', table_name='document_processing_results')
    op.drop_table('document_processing_results')
    op.drop_index('idx_vital_user_id', table_name='clinical_vital_signs')
    op.drop_index('idx_vital_measurement_date', table_name='clinical_vital_signs')
    op.drop_index('idx_vital_document_id', table_name='clinical_vital_signs')
    op.drop_index('idx_vital_deleted_at', table_name='clinical_vital_signs')
    op.drop_table('clinical_vital_signs')
    op.drop_index('idx_procedure_user_id', table_name='clinical_procedures')
    op.drop_index('idx_procedure_performed_date', table_name='clinical_procedures')
    op.drop_index('idx_procedure_document_id', table_name='clinical_procedures')
    op.drop_index('idx_procedure_deleted_at', table_name='clinical_procedures')
    op.drop_index('idx_procedure_cpt', table_name='clinical_procedures')
    op.drop_table('clinical_procedures')
    op.drop_index('idx_medication_user_id', table_name='clinical_medications')
    op.drop_index('idx_medication_rxnorm', table_name='clinical_medications')
    op.drop_index('idx_medication_is_active', table_name='clinical_medications')
    op.drop_index('idx_medication_document_id', table_name='clinical_medications')
    op.drop_index('idx_medication_deleted_at', table_name='clinical_medications')
    op.drop_table('clinical_medications')
    op.drop_index('idx_lab_user_id', table_name='clinical_lab_results')
    op.drop_index('idx_lab_test_name', table_name='clinical_lab_results')
    op.drop_index('idx_lab_test_date', table_name='clinical_lab_results')
    op.drop_index('idx_lab_loinc', table_name='clinical_lab_results')
    op.drop_index('idx_lab_is_abnormal', table_name='clinical_lab_results')
    op.drop_index('idx_lab_document_id', table_name='clinical_lab_results')
    op.drop_index('idx_lab_deleted_at', table_name='clinical_lab_results')
    op.drop_table('clinical_lab_results')
    op.drop_index('idx_immunization_vaccine', table_name='clinical_immunizations')
    op.drop_index('idx_immunization_user_id', table_name='clinical_immunizations')
    op.drop_index('idx_immunization_document_id', table_name='clinical_immunizations')
    op.drop_index('idx_immunization_deleted_at', table_name='clinical_immunizations')
    op.drop_index('idx_immunization_admin_date', table_name='clinical_immunizations')
    op.drop_table('clinical_immunizations')
    op.drop_index('idx_condition_user_id', table_name='clinical_conditions')
    op.drop_index('idx_condition_status', table_name='clinical_conditions')
    op.drop_index('idx_condition_icd10', table_name='clinical_conditions')
    op.drop_index('idx_condition_document_id', table_name='clinical_conditions')
    op.drop_index('idx_condition_deleted_at', table_name='clinical_conditions')
    op.drop_table('clinical_conditions')
    op.drop_index('idx_allergy_user_id', table_name='clinical_allergies')
    op.drop_index('idx_allergy_severity', table_name='clinical_allergies')
    op.drop_index('idx_allergy_is_active', table_name='clinical_allergies')
    op.drop_index('idx_allergy_document_id', table_name='clinical_allergies')
    op.drop_index('idx_allergy_deleted_at', table_name='clinical_allergies')
    op.drop_table('clinical_allergies')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('idx_audit_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_document_id', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_document_user_id', table_name='documents')
    op.drop_index('idx_document_type', table_name='documents')
    op.drop_index('idx_document_date', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
